// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu0mec6Gk8KSJKveBMAMOILrGyRZ63it0',
    appId: '1:358315244059:web:d3d766c5de642add9296be',
    messagingSenderId: '358315244059',
    projectId: 'e-commerce-5feb0',
    authDomain: 'e-commerce-5feb0.firebaseapp.com',
    storageBucket: 'e-commerce-5feb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF3gp2hWgcgDZUZr2OCUyzbIDB4jeMadI',
    appId: '1:358315244059:android:c1ed319896cd79d09296be',
    messagingSenderId: '358315244059',
    projectId: 'e-commerce-5feb0',
    storageBucket: 'e-commerce-5feb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnv9fVZ_4iHOK-R2Au-cF0YEBAhTrgBR8',
    appId: '1:358315244059:ios:1c29220d7eb6e1349296be',
    messagingSenderId: '358315244059',
    projectId: 'e-commerce-5feb0',
    storageBucket: 'e-commerce-5feb0.firebasestorage.app',
    iosBundleId: 'com.store.eCommerce',
  );
}
